//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_3_capas_ModasDelCentro.Catalogos.Usuarios
{


    public partial class RegistroUsuarios
    {
    }
}
